[tool.poetry]
name = "bookstore"
version = "0.1.5"
description = "docker Class"
authors = ["Patrick Passarella <pshaggy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
